name: Post tweet

on:
  push:
    branches:
      - main

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install dependencies
        run: |
          go get github.com/sivchari/gotwtr

      - name: Get git diff
        run: |
          git diff HEAD^ HEAD > diff.json

      - name: Build and run
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          export TWEET_TEXT=$(cat diff.json)
          go build main.go
          ./main
