name: Post tweet

on:
  push:
    branches:
      - main

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install dependencies
        run: |
          go get github.com/dghubble/go-twitter/twitter
          go get github.com/dghubble/oauth1

      - name: test print
        run: echo "test print"

      - name: Build and run
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          go build main.go
          ./main
